; directed: Corner cases: pointer ordering, flag preservation, link registers, reserved codes.
; Generated by tools/progs.py. Expected final data memory is computed there in plain Python.
        LDI R6,0x0100
        LDI R1,0x1111
        PUSH R1,[R6]              ; pre-decrement: R6 = 0x00FF, mem[0x00FF] = 0x1111
        ST R6,[0xA000]
        LD R2,[0x00FF]
        ST R2,[0xA001]
        LDI R3,0x0200
        POP R3,[R3]               ; rd == rs: the loaded value wins over the increment
        ST R3,[0xA002]
        LDI R4,0x0300
        LDI R5,0x00AA
        STX R5,[R4]
        LD R4,[0x0300]
        ST R4,[0xA003]
        LDI R1,5
        CMP R1,R1                 ; Z=1 C=1
        LDI R2,0                  ; LDI changes Z,N only: C must stay 1
        LDI R7,0
        BHS cok
        LDI R7,0xBAD
cok:    ST R7,[0xA004]
        LDI R7,1
        LDI R1,0xFFFF
        ADDI R1,1                 ; R1=0, Z=1, C=1 (LDI above would clobber Z, so it comes first)
        BEQ zok
        LDI R7,0
zok:    BLO zbad                  ; C=1 so LO is not taken
        ST R7,[0xA005]
        BAL R5,after              ; link = address of the next instruction (label back)
back:   LDI R7,0
        ST R7,[0xA006]
        HALT
after:  LDI R4,back
        LDI R7,1
        CMP R4,R5
        BEQ linkok
        LDI R7,0
linkok: ST R7,[0xA006]
        BAL R0,skip1              ; link register R0: nothing is written
skip1:  LDI R7,1
        ST R7,[0xA007]
        LDI R1,1
        CMP R1,R1                 ; Z=1
        BNE never                 ; not taken: must still consume its extension word
        LDI R7,1
        ST R7,[0xA008]
        .word 0x000E              ; function 14: no such function, executes as NOP
        .word 0x003F              ; function 63: NOP
        .word 0x01C0              ; NOP with garbage in rd/rs
        .word 0x001F              ; BCC with cc=15 (reserved): never taken, consumes next word
        .word 0x0000
        LDI R7,1
        ST R7,[0xA009]
        LDI R1,tgt
        LDI R2,0
        JALR R2,R1                ; R2 = return address, jump to tgt
back2:  HALT
tgt:    LDI R4,back2
        LDI R7,1
        CMP R4,R2
        BEQ jalrok
        LDI R7,0
jalrok: ST R7,[0xA00A]
        LDI R1,tgt2
        JR R1
        HALT
tgt2:   LDI R7,1
        ST R7,[0xA00B]
        LDI R1,0x7FFF
        ADDI R1,1                 ; signed overflow: V=1, N=1
        BVC zbad                  ; V=1 so VC is not taken
        BLT zbad                  ; N == V so LT is not taken
        LDI R7,1
        ST R7,[0xA00C]
        HALT
zbad:   HALT
never:  HALT
