; crc16: CRC-16/CCITT-FALSE over 24 bytes using shifts and the carry flag.
; Generated by tools/progs.py. Expected final data memory is computed there in plain Python.
LDI R1,120
ST R1,[37888]
LDI R1,155
ST R1,[37889]
LDI R1,52
ST R1,[37890]
LDI R1,202
ST R1,[37891]
LDI R1,245
ST R1,[37892]
LDI R1,79
ST R1,[37893]
LDI R1,46
ST R1,[37894]
LDI R1,34
ST R1,[37895]
LDI R1,10
ST R1,[37896]
LDI R1,205
ST R1,[37897]
LDI R1,148
ST R1,[37898]
LDI R1,30
ST R1,[37899]
LDI R1,113
ST R1,[37900]
LDI R1,184
ST R1,[37901]
LDI R1,141
ST R1,[37902]
LDI R1,88
ST R1,[37903]
LDI R1,54
ST R1,[37904]
LDI R1,134
ST R1,[37905]
LDI R1,109
ST R1,[37906]
LDI R1,13
ST R1,[37907]
LDI R1,133
ST R1,[37908]
LDI R1,139
ST R1,[37909]
LDI R1,99
ST R1,[37910]
LDI R1,84
ST R1,[37911]

        LDI R1,0xFFFF
        LDI R2,37888
        LDI R3,24
        LDI R7,0x1021
bytel:  LDX R4,[R2]
        SHL R4
        SHL R4
        SHL R4
        SHL R4
        SHL R4
        SHL R4
        SHL R4
        SHL R4
        XOR R1,R4
        LDI R5,8
bitl:   SHL R1
        BCC nopoly
        XOR R1,R7
nopoly: ADDI R5,-1
        BNE bitl
        ADDI R2,1
        ADDI R3,-1
        BNE bytel
        ST R1,[37920]
        HALT
