; recursion: Recursive factorial and Fibonacci with PUSH/POP/CALL/RET and a software stack in R6.
; Generated by tools/progs.py. Expected final data memory is computed there in plain Python.
LDI R6,0xE000
LDI R1,0
CALL fact
ST R2,[37120]
LDI R1,1
CALL fact
ST R2,[37121]
LDI R1,2
CALL fact
ST R2,[37122]
LDI R1,3
CALL fact
ST R2,[37123]
LDI R1,4
CALL fact
ST R2,[37124]
LDI R1,5
CALL fact
ST R2,[37125]
LDI R1,6
CALL fact
ST R2,[37126]
LDI R1,7
CALL fact
ST R2,[37127]
LDI R1,8
CALL fact
ST R2,[37128]
LDI R1,0
CALL fib
ST R2,[37152]
LDI R1,1
CALL fib
ST R2,[37153]
LDI R1,2
CALL fib
ST R2,[37154]
LDI R1,3
CALL fib
ST R2,[37155]
LDI R1,4
CALL fib
ST R2,[37156]
LDI R1,5
CALL fib
ST R2,[37157]
LDI R1,6
CALL fib
ST R2,[37158]
LDI R1,7
CALL fib
ST R2,[37159]
LDI R1,8
CALL fib
ST R2,[37160]
LDI R1,9
CALL fib
ST R2,[37161]
LDI R1,10
CALL fib
ST R2,[37162]
HALT

fact:   CMP R1,R0
        BNE frec
        LDI R2,1
        RET
frec:   PUSH R7
        PUSH R1
        ADDI R1,-1
        CALL fact
        POP R1
        CALL mul
        MOV R2,R4
        POP R7
        RET
fib:    LDI R3,2
        CMP R1,R3
        BHS fibrec
        MOV R2,R1
        RET
fibrec: PUSH R7
        PUSH R1
        ADDI R1,-1
        CALL fib
        POP R1
        PUSH R2
        ADDI R1,-2
        CALL fib
        POP R3
        ADD R2,R3
        POP R7
        RET

mul:    LDI R3,0            ; R3:R4 = R1 * R2 (32-bit product), R1 and R2 destroyed
        LDI R4,0
        LDI R5,0
mloop:  CMP R2,R0
        BEQ mdone
        SHR R2
        BCC mskip
        ADD R4,R1
        ADC R3,R5
mskip:  SHL R1
        ADC R5,R5
        JMP mloop
mdone:  RET
