; sort_unsigned: Bubble sort of 12 words with LDX/STX and an unsigned compare (BLS).
; Generated by tools/progs.py. Expected final data memory is computed there in plain Python.
LDI R1,31190
ST R1,[37632]
LDI R1,32768
ST R1,[37633]
LDI R1,62135
ST R1,[37634]
LDI R1,8588
ST R1,[37635]
LDI R1,32767
ST R1,[37636]
LDI R1,33994
ST R1,[37637]
LDI R1,65535
ST R1,[37638]
LDI R1,61638
ST R1,[37639]
LDI R1,32767
ST R1,[37640]
LDI R1,65535
ST R1,[37641]
LDI R1,19873
ST R1,[37642]
LDI R1,0
ST R1,[37643]

        LDI R1,37632
        LDI R2,11
outer:  MOV R4,R1
        MOV R3,R2
inner:  LDX R5,[R4]
        MOV R6,R4
        ADDI R6,1
        LDX R7,[R6]
        CMP R5,R7
        BLS noswap
        STX R7,[R4]
        STX R5,[R6]
noswap: ADDI R4,1
        ADDI R3,-1
        BNE inner
        ADDI R2,-1
        BNE outer
        HALT
